// <auto-generated />
using System;
using CouponManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CouponManagementSystem.Migrations
{
    [DbContext(typeof(Couponcontext))]
    partial class CouponcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CouponManagementSystem.Entities.Coupon", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("count")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("expirationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("ownerId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique()
                        .HasFilter("\"deletedAt\" IS NULL");

                    b.HasIndex("ownerId");

                    b.ToTable("Coupon");
                });

            modelBuilder.Entity("CouponManagementSystem.Entities.Couponclaim", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("claimedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("couponId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.HasIndex("couponId", "userId")
                        .IsUnique()
                        .HasFilter("\"deletedAt\" IS NULL");

                    b.ToTable("Couponclaim");
                });

            modelBuilder.Entity("CouponManagementSystem.Entities.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique()
                        .HasFilter("\"deletedAt\" IS NULL");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CouponManagementSystem.Entities.Coupon", b =>
                {
                    b.HasOne("CouponManagementSystem.Entities.User", "owner")
                        .WithMany("coupons")
                        .HasForeignKey("ownerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("owner");
                });

            modelBuilder.Entity("CouponManagementSystem.Entities.Couponclaim", b =>
                {
                    b.HasOne("CouponManagementSystem.Entities.Coupon", "coupon")
                        .WithMany("claims")
                        .HasForeignKey("couponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CouponManagementSystem.Entities.User", "user")
                        .WithMany("claims")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("coupon");

                    b.Navigation("user");
                });

            modelBuilder.Entity("CouponManagementSystem.Entities.Coupon", b =>
                {
                    b.Navigation("claims");
                });

            modelBuilder.Entity("CouponManagementSystem.Entities.User", b =>
                {
                    b.Navigation("claims");

                    b.Navigation("coupons");
                });
#pragma warning restore 612, 618
        }
    }
}
